name: analyze
on: [push, pull_request]

concurrency:
  group: ${ {github.event_name }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{github.event_name == 'pull_request'}}

jobs:
  CI:
    strategy:
      matrix:
        directory: ['CI/macOS']
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: clone benchamrk monitor
        run: |
          pwd
          ls -la
          git clone https://github.com/bensanmorris/benchmark_monitor.git
      - name: prepare python env
        run: |
          cd benchmark_monitor
          pwd
          ls -la
          pip install -r requirements.txt
      - name: analyze benchmark results
        run: |
          cd benchmark_monitor
          pwd
          ls -la
          python3 ./benchmark_monitor.py -d ../benchmark/${{ matrix.directory }} -o out
      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out
